[package]
name = "ecsimple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "^0.2"
lazy_static = "^1.4.0"
chrono = "^0.4.0"
num-bigint = "^0.4.3"
hex = "^0.4.3"
